export const INTEGRATION_CATALOG = {
    email: [
        "Sendgrid Email Gateway",
        "Amazon SES Email Gateway",
        "SMTP Email Gateway",
        "Monshaat EMAIL Gateway",
        "SMTP Relay Email Gateway",
        "SMTP Relay V2 Email Gateway",
        "HRSD EMAIL Gateway",
        "Gulf African Bank EMAIL Gateway",
        "SMTP Email Gateway (IP Auth)",
        "SMTP Email Gateway (sender name)",
        "Zatca Notification Engine Email Gateway",
        "Monshaat V2 Email Gateway",
        "DGE Email Gateway",
        "Atidi Email Gateway",
        "Nivabupa infobip email gateway",
        "HRSD V2 EMAIL Gateway",
        "FCMB Email Gateway",
        "Mobily Email Gateway",
        "MODON Email Gateway",
        "Medgulf Email Gateway",
        "BOJ Email Gateway",
        "Microsoft Graph Email Gateway",
        "SMTP TLS Email Gateway",
        "SMTP Azure OAuth Email Gateway"
    ],
    sms: [
        "Unifonic SMS Gateway",
        "Unifonic V2 SMS Gateway",
        "SmartSms SMS Gateway",
        "SmartSms SMS Gateway - Arabic",
        "routemobile SMS Gateway India",
        "routemobile SMS Gateway International",
        "GAZT SMS Gateway",
        "Alfa Cell SMS Gateway",
        "Ezee SMS Gateway",
        "Dr. Fakeeh Care SMS Gateway",
        "Cequens, Dewan Alrasayel SMS Gateway",
        "Cequens, SAT SMS Gateway",
        "SAT Bulk SMS Gateway",
        "MobiShastra SMS Gateway",
        "Medgulf SMS Gateway",
        "Monshaat SMS Gateway",
        "HRSD SMS Gateway",
        "Elitbuzz SMS Gateway",
        "Nimbusit SMS Gateway",
        "EchoMobile SMS Gateway",
        "ACL Gateway SMS Gateway",
        "Infobip SMS Gateway",
        "Gulf African Bank SMS Gateway",
        "Infinito SMS Gateway (only for KSA)",
        "Onfon SMS Gateway",
        "Inuka Africa SMS Gateway",
        "SMS Connect Service SMS Gateway",
        "Yamamah SMS Gateway",
        "Sec SMS Gateway",
        "Kalaam Telecom SMS Gateway",
        "AU Bank SMS Gateway",
        "Karix SMS Gateway",
        "Allianz Saudi Fransi SMS Gateway",
        "Yamamah OSI SMS Gateway",
        "Alghanim SMS Gateway",
        "Zatca Notification Engine SMS Gateway",
        "Unifonic V3 SMS Gateway",
        "Yamamah SAIP SMS Gateway",
        "NCBA Notifications SMS Gateway",
        "SmartSms SMS Gateway - Adeo",
        "Monshaat V2 SMS Gateway",
        "Unifonic V4 SMS Gateway",
        "Unifonic V5 SMS Gateway",
        "MTECH SMS Gateway IP",
        "SMPP SMS Gateway",
        "Multi SMPP SMS Gateway",
        "KCB SMS Gateway",
        "Advanta SMS Gateway",
        "Advanta Bulk SMS Gateway",
        "AU Bank APIGEE SMS",
        "NAJM SMS gateway",
        "Alinma SMS Gateway",
        "Fusio SMS Gateway",
        "Reson8 SMS Gateway",
        "Reson8 SMS Campaign Gateway",
        "Unifonic V6 SMS Gateway",
        "AMH SMS Gateway",
        "SEEC SMS Gateway",
        "HRSD V2 SMS Gateway",
        "Econet SMS Gateway",
        "FCMB SMS Gateway",
        "REDF SMS Gateway",
        "Twilio SMS Gateway",
        "Falcon(future club) SMS Gateway",
        "Mobily SMS Gateway",
        "MOS SMS Gateway",
        "WRTH Unifonic SMS Gateway",
        "MODON SMS Gateway",
        "Medgulf V2 SMS Gateway",
        "AAmotors SMS Gateway",
        "FCC SMS Gateway",
        "HRDA SMS Gateway",
        "BOJ SMS Gateway",
        "RELAAM SMS Gateway",
        "DGE SMS Gateway",
        "DEWA SMS Gateway"
    ],
    whatsapp: [
        "Whatsapp Gateway",
        "Sunshine Whatsapp Gateway",
        "Infobip Whatsapp Gateway",
        "Value First Whatsapp Gateway",
        "Tree Whatsapp Gateway",
        "Whatsapp Cloud Business Gateway",
        "Sendbee Whatsapp Gateway",
        "Freshchat Whatsapp Gateway",
        "Smatbot Whatsapp Gateway",
        "Infobip NCBA Whatsapp Gateway",
        "Infobip NCBA Template Whatsapp Gateway",
        "Karix Whatsapp Gateway",
        "Unifonic conversation Whatsapp Business Gateway",
        "REDF Whatsapp Gateway",
        "Mobily Whatsapp Gateway",
        "AU Bank WhatsApp Gateway",
        "FCC Whatsapp Gateway",
        "BOJ WhatsApp Gateway",
        "REDF Whatsapp V1 Gateway"
    ]
};
